spring:
  application:
    name: config-client
  cloud:
    config:
      # \u5F00\u542F\u5FEB\u901F\u54CD\u5E94
      fail-fast: true
      retry:
        # \u8BF7\u6C42\u91CD\u8BD5\u7684\u521D\u59CB\u95F4\u9694\u65F6\u95F4
        initial-interval: 1000
        # \u6700\u5927\u91CD\u8BD5\u6B21\u6570
        max-attempts: 6
        # \u91CD\u8BD5\u65F6\u95F4\u95F4\u9694
        multiplier: 1.1
        # \u6700\u5927\u95F4\u9694\u65F6\u95F4
        max-interval: 2000
server:
  port: 8082



# \u6DFB\u52A0\u52A8\u6001\u5237\u65B0\u8282\u70B9
management:
  endpoints:
    web:
      exposure:
        include: refresh
