

#spring.rabbitmq.host=122.51.115.148
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest
#spring.rabbitmq.port=5672


spring:
  rabbitmq:
    host: 122.51.115.148
    username: guest
    password: guest
    port: 5672
  cloud:
    stream:
      bindings:
        pikachues-input:
          destination: pikachues-topic
          group: g1


# 发送接收通道名称不同，但是主题（广播站名称）称必须相同
#  spring.cloud.stream.bindings.pikachues-input.destination=pikachues-topic
#  spring.cloud.stream.bindings.pikachues-output.destination=pikachues-topic
#
#  # 消息分组避免重复消费
#  spring.cloud.stream.bindings.pikachues-input.group=g1
#  spring.cloud.stream.bindings.pikachues-output.group=g1
server:
  port: 8081
