server:
  port: 8083
eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8083/eureka
spring:
  application:
    name: eureka-server-bus
