spring:
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaA:1111/eureka
  instance:
    hostname: eurekaB
server:
  port: 1112
